Repository pnnl/ruleset-checking-tool, pull requests merged in 2024-09, with the labels that each got.

#1518 update 5_2
  rct229/rulesets/ashrae9012019/section5/section5rule2.py
  rct229/ruletest_engine/ruletest_jsons/ashrae9012019/section5/rule_5_2.json
Labels: section5

#1400 Rds/kjw/function get swh bats and swh use
  docs/_toc.md
  docs/ruleset_functions/get_SWH_bats_and_SWH_use.md
Labels: rds, ReadytoMerge, section11

#1401 Rds/kjw/function get swh uses associated with each building segment
  docs/_toc.md
  docs/ruleset_functions/get_SWH_uses_associated_with_each_building_segment.md
Labels: rds, ReadytoMerge, section11

#1402 Rds/kjw/function get building segment swh bat
  docs/_toc.md
  docs/ruleset_functions/get_building_segment_SWH_bat.md
Labels: rds, ReadytoMerge, section11

#1403 Rds/kjw/function get swh equipment associated with each swh bat
  docs/_toc.md
  docs/ruleset_functions/get_SWH_components_associated_with_each_SWH_bat.md
Labels: rds, ReadytoMerge, section11

#1404 Create get_SWH_equipment_associated_with_each_swh_distribution_system.md
  docs/_toc.md
  docs/ruleset_functions/get_swh_components_associated_with_each_swh_distribution_system.md
Labels: rds, ReadytoMerge, section11

#1405 Create get_swh_equipment_type.md
  docs/_toc.md
  docs/ruleset_functions/get_swh_equipment_type.md
Labels: rds, ReadytoMerge, section11

#1406 Create get_energy_required_to_heat_swh_use.md
  docs/_toc.md
  docs/ruleset_functions/get_energy_required_to_heat_swh_use.md
Labels: rds, ReadytoMerge, section11

#1501 RCT/YJ/get swh equipment type function
  rct229/rulesets/ashrae9012019/ruleset_functions/get_swh_equipment_type.py
  rct229/rulesets/ashrae9012019/ruleset_functions/get_swh_equipment_type_test.py
Labels: ReadytoMerge, functions, section11

#1407 Create get_spaces_served_by_SWH_use.md
  docs/_toc.md
  docs/ruleset_functions/get_spaces_served_by_SWH_use.md
Labels: rds, ReadytoMerge, section11

#1379 Rds/kjw/rule 11 13
  docs/_toc.md
  docs/section11/Rule11-13.md
Labels: rds, ReadytoMerge, section11

#1378 Create Rule11-12.md
  docs/_toc.md
  docs/section11/Rule11-12.md
Labels: rds, ReadytoMerge, section11

#1374 Create Rule_11-11.md
  docs/_toc.md
  docs/section11/Rule11-11.md
Labels: rds, ReadytoMerge, section11

#1371 Create Rule_11-7.md
  docs/_toc.md
  docs/section11/Rule11-7.md
Labels: rds, ReadytoMerge, section11

#1370 RDS Rule11-6.md
  docs/_toc.md
  docs/section11/Rule11-6.md
Labels: rds, ReadytoMerge, section11

#1267 Add is_tolerance_fail method for Section 5 to 6
  rct229/rulesets/ashrae9012019/section5/section5rule1.py
  rct229/rulesets/ashrae9012019/section5/section5rule10.py
  rct229/rulesets/ashrae9012019/section5/section5rule12.py
  rct229/rulesets/ashrae9012019/section5/section5rule13.py
  rct229/rulesets/ashrae9012019/section5/section5rule14.py
  rct229/rulesets/ashrae9012019/section5/section5rule15.py
  rct229/rulesets/ashrae9012019/section5/section5rule16.py
  rct229/rulesets/ashrae9012019/section5/section5rule19.py
  rct229/rulesets/ashrae9012019/section5/section5rule20.py
  rct229/rulesets/ashrae9012019/section5/section5rule21.py
  rct229/rulesets/ashrae9012019/section5/section5rule23.py
  rct229/rulesets/ashrae9012019/section5/section5rule24.py
  rct229/rulesets/ashrae9012019/section5/section5rule25.py
  rct229/rulesets/ashrae9012019/section5/section5rule26.py
  rct229/rulesets/ashrae9012019/section5/section5rule27.py
  rct229/rulesets/ashrae9012019/section5/section5rule28.py
  rct229/rulesets/ashrae9012019/section5/section5rule29.py
  rct229/rulesets/ashrae9012019/section5/section5rule30.py
  rct229/rulesets/ashrae9012019/section5/section5rule31.py
  rct229/rulesets/ashrae9012019/section5/section5rule32.py
  rct229/rulesets/ashrae9012019/section5/section5rule35.py
  rct229/rulesets/ashrae9012019/section5/section5rule36.py
  rct229/rulesets/ashrae9012019/section5/section5rule37.py
  rct229/rulesets/ashrae9012019/section5/section5rule39.py
  rct229/rulesets/ashrae9012019/section5/section5rule4.py
  rct229/rulesets/ashrae9012019/section5/section5rule40.py
  rct229/rulesets/ashrae9012019/section5/section5rule6.py
  rct229/rulesets/ashrae9012019/section5/section5rule8.py
  rct229/rulesets/ashrae9012019/section6/section6rule1.py
  rct229/rulesets/ashrae9012019/section6/section6rule2.py
  rct229/rulesets/ashrae9012019/section6/section6rule3.py
  rct229/rulesets/ashrae9012019/section6/section6rule4.py
  rct229/rulesets/ashrae9012019/section6/section6rule5.py
  rct229/ruletest_engine/ruletest_jsons/ashrae9012019/section5/rule_5_15.json
Labels: enhancement
