Repository pnnl/ruleset-checking-tool, pull requests merged in 2025-06, with the labels that each got.

#949 Rds/cml/function get hvac systems primarily serving comp rooms
  docs/ruleset_functions/get_HVAC_systems_primarily_serving_comp_rooms.md
Labels: rds, ReadytoMerge, functions, section19

#1503 RDS/JDJ/19-10 "Fail unless"
  docs/section19/Rule19-10.md
Labels: rds, ReadytoMerge

#1751 RCT/JX/section12 schema update 0.1.7
  rct229/rulesets/ashrae9012019/ruleset_functions/compare_schedules.py
  rct229/rulesets/ashrae9012019/section12/section12rule2.py
  rct229/rulesets/ashrae9012019/section12/section12rule3.py
  rct229/rulesets/ashrae9012019/section12/section12rule4.py
Labels: schema, readyForReview

#1752 RCT/JX/section22 schema update 0.1.7
  rct229/rulesets/ashrae9012019/section22/section22rule17.py
  rct229/rulesets/ashrae9012019/section22/section22rule21.py
  rct229/rulesets/ashrae9012019/section22/section22rule31.py
Labels: schema, readyForReview

#1753 RCT/JX/section23 schema update 0.1.7
  rct229/rulesets/ashrae9012019/section23/section23rule4.py
  rct229/rulesets/ashrae9012019/section23/section23rule8.py
Labels: schema, readyForReview

#1734 RS/YJ/Rule 23-3 (Updated logic)
  rct229/rulesets/ashrae9012019/section23/section23rule3.py
Labels: section23, readyForReview

#879 Rds/kjw/rule 23 3
  docs/section23/Rule23-3.md
Labels: rds, ReadytoMerge, section23
